# Header
menu:
  Home: /
#  Tags: /tags

rss: /atom.xml

# User Info
user_name: Prajakarana
user_avatar: https://prajakarana.u91.co/2017/08/13/Prajakarana-Upendra%E2%80%99s-tentative-name-for-party/13BGUPENDRA512.jpg?raw=true
user_location: Bengaulru, Karnataka
user_description: "by Uppi"
user_contact: prajaakaarana1@gmail.com
user_introduction: "people-centric democracy"
github_username: prajakarana
twitter_username: NimmaUpendra
weibo_username:
zhihu_username:
facebook_username:
linkedin_username:
author_avatar: https://s.gravatar.com/avatar/644b3c2ba34959ac56b181fcc6937d2b?size=496&default=retro
author_name: Manjesh V
# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: false
livere_uid: MTAyMC8yOTE4Ni81NzUz

use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

# Miscellaneous
google_analytics: UA-104512304-1
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:


